title: Ahmad Fariz Dwi Putra
description: Little programmer who likes to try and sometimes gives up easily
site_title: 'Ahmad Fariz Dwi Putra'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ahmadfariz
blog_url: ahmadfariz.my.id/
email: ahmudhakim@gmail.com
facebook: ahmadfarizdwiputra
instagram: ahmadfarizdwiputra

# absolute or relative
profile_picture: assets/images/pp.png

# Google Analytics ID
google_analytics: 