title: Ahmad Fariz Dwi Putra
description: 
site_title: 'Ahmad Fariz Dwi Putra'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ahmadfariz
blog_url: ahmadfariz.my.id/
email: ahmudhakim@gmail.com

# absolute or relative
profile_picture: assets/images/pp.png

# Google Analytics ID
google_analytics: 